"""Rig-side injection of regtest "trampoline" nodes into a running Electrum.

WHY. Electrum has two sources for ``LNWallet.suggest_peer()`` -- the node the
plugin falls back to when the user has configured no preferred partner -- and on
regtest neither can produce anything:

  * trampoline mode (``use_gossip=false``, what the rig uses):
    ``trampoline.hardcoded_trampoline_nodes()`` has entries for mainnet / testnet /
    signet only and returns ``{}`` for regtest, so Electrum's
    ``random.choice(list({}.values()))`` raises ``IndexError``;
  * gossip mode: ``LNRater`` needs a synced *public* channel graph with
    long-lived, well-connected nodes, which a two-node regtest never has.

So without help, the plugin's suggested-peer path cannot be exercised end to end
-- only its preferred-partners path (which is what the rig normally configures via
``set_client_channel_peer``). This module supplies the missing piece by making
regtest look like a network that *has* a trampoline node: the rig's own swap
partner.

HOW. :func:`write_sitecustomize` drops a ``sitecustomize.py`` into a scratch dir.
A test puts that dir on ``PYTHONPATH`` and sets ``RIG_TRAMPOLINE_JSON`` *before*
the rig launches, so every child python process -- the Electrum client daemon
included -- imports it at interpreter start. It installs a meta-path hook that
patches ``electrum.trampoline.hardcoded_trampoline_nodes`` the moment that module
is imported, which is necessarily before ``lnworker`` binds the name with its
``from .trampoline import ...``. The replacement re-reads the JSON file on *every*
call, so the node list can be written (or changed) after the daemon is already
running -- the rig only learns the partner's node id part-way through bring-up.

The hook is inert unless ``RIG_TRAMPOLINE_JSON`` is set, defers all Electrum
imports to their natural time (importing Electrum at interpreter start would slow
down every ``electrum_cli`` call in the rig), and swallows its own errors so test
scaffolding can never take the daemon down. Nothing here modifies the Electrum
checkout or the plugin.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Dict

from . import paths

# Env var naming the JSON file with the nodes to advertise. Read on every call to
# the patched function, so the file may appear after the daemon has started.
TRAMPOLINE_JSON_ENV: str = "RIG_TRAMPOLINE_JSON"

# Where the generated scaffolding lives (under the wiped-every-launch run dir).
INJECT_DIR: Path = paths.RUN_DIR / "inject"
TRAMPOLINE_JSON: Path = INJECT_DIR / "trampoline_nodes.json"

_SITECUSTOMIZE = '''\
"""Rig test scaffolding -- GENERATED by rig/trampoline_stub.py, do not edit.

Patches electrum.trampoline.hardcoded_trampoline_nodes() to serve the node list in
$RIG_TRAMPOLINE_JSON, so regtest can have a "trampoline" node (see the generator's
module docstring). Inert unless that variable is set.
"""
import importlib.abc
import json
import os
import sys

_ENV = "RIG_TRAMPOLINE_JSON"
_TARGET = "electrum.trampoline"


def _patch(module):
    original = module.hardcoded_trampoline_nodes

    def hardcoded_trampoline_nodes():
        path = os.environ.get(_ENV)
        if not path or not os.path.exists(path):
            return original()          # nothing supplied (yet): real behaviour
        with open(path) as fh:
            entries = json.load(fh)
        return {
            name: module.LNPeerAddr(host=entry["host"], port=int(entry["port"]),
                                    pubkey=bytes.fromhex(entry["pubkey"]))
            for name, entry in entries.items()
        }

    module.hardcoded_trampoline_nodes = hardcoded_trampoline_nodes


class _PatchTrampolineFinder(importlib.abc.MetaPathFinder):
    """Delegates to the normal import machinery, then patches the module."""

    def find_spec(self, fullname, path=None, target=None):
        if fullname != _TARGET:
            return None
        spec = None
        for finder in sys.meta_path:
            if finder is self:
                continue
            try:
                spec = finder.find_spec(fullname, path, target)
            except (AttributeError, ImportError):
                continue
            if spec is not None:
                break
        if spec is None or spec.loader is None:
            return spec
        original_exec = getattr(spec.loader, "exec_module", None)
        if original_exec is None:
            return spec

        def exec_module(module):
            original_exec(module)
            try:
                _patch(module)
            except Exception:
                pass                   # never break Electrum over scaffolding
        try:
            spec.loader.exec_module = exec_module
        except (AttributeError, TypeError):
            pass
        return spec


if os.environ.get(_ENV):
    sys.meta_path.insert(0, _PatchTrampolineFinder())
'''


def write_sitecustomize() -> Path:
    """Create the scaffolding dir with its ``sitecustomize.py`` and return the dir
    to put on ``PYTHONPATH``."""
    INJECT_DIR.mkdir(parents=True, exist_ok=True)
    (INJECT_DIR / "sitecustomize.py").write_text(_SITECUSTOMIZE)
    return INJECT_DIR


def env_for(existing: Dict[str, str]) -> Dict[str, str]:
    """``existing`` plus the two variables the hook needs (``PYTHONPATH`` prepended,
    never replaced). Call before the rig spawns anything -- child processes inherit
    the environment as it stands at spawn time."""
    inject_dir = write_sitecustomize()
    env = dict(existing)
    previous = env.get("PYTHONPATH", "")
    env["PYTHONPATH"] = (f"{inject_dir}{os.pathsep}{previous}" if previous
                         else str(inject_dir))
    env[TRAMPOLINE_JSON_ENV] = str(TRAMPOLINE_JSON)
    return env


def advertise(node_id: str, host: str, port: int, *, name: str = "rig partner") -> None:
    """Publish one node as the network's only trampoline node. Takes effect on the
    running daemon's next lookup -- the patched function re-reads this file each
    time.

    ``node_id`` may be a bare pubkey or a full ``pubkey@host:port`` connect string
    (which is what ``wait_lightning_ready`` / ``rig.partner_nodeid`` hand back); any
    attached address is stripped, since the address is passed separately and the
    JSON must carry a pure hex pubkey.
    """
    pubkey = node_id.strip().split("@", 1)[0].strip().lower()
    bytes.fromhex(pubkey)              # fail here, not inside the daemon
    INJECT_DIR.mkdir(parents=True, exist_ok=True)
    TRAMPOLINE_JSON.write_text(json.dumps(
        {name: {"host": host, "port": int(port), "pubkey": pubkey}}, indent=2))


def clear() -> None:
    """Remove the advertised list, restoring Electrum's real (empty on regtest)
    behaviour."""
    TRAMPOLINE_JSON.unlink(missing_ok=True)
